# Copyright(c) 2021 aasaam software development group
version: "3"

services:
  # backend
  htm-backend:
    image: ghcr.io/aasaam/htm-management-backend:latest
    depends_on:
      - htm-mongo
      - htm-redis
    container_name: htm-backend
    # entrypoint: tail -f /dev/null
    volumes:
      # change during deploy it's just a test
      - ./root.pem:/app/api/conf/root.pem
    environment:
      ASM_PUBLIC_APP_TEST: "false"
      ASM_AUTH_HMAC_SECRET: ${ASM_AUTH_HMAC_SECRET:-}
      ASM_PUBLIC_APP_NS: ${ASM_PUBLIC_APP_NS:-htm}
      ASM_AUTH_COOKIE: ${ASM_AUTH_COOKIE:-htm-auth-token}
      ASM_AUTH_REFRESH_COOKIE: ${ASM_AUTH_REFRESH_COOKIE:-htm-auth-refresh}
      ASM_PUBLIC_AUTH_TOKEN_TTL: ${ASM_PUBLIC_AUTH_TOKEN_TTL:-900}
      ASM_PUBLIC_AUTH_REFRESH_TOKEN_TTL: ${ASM_PUBLIC_AUTH_REFRESH_TOKEN_TTL:-43200}

  # front and nginx
  htm-web:
    image: ghcr.io/aasaam/htm-management-web:latest
    depends_on:
      - htm-backend
    container_name: htm-web
    ports:
      - 80:80
      - 443:443
    environment:
      ASM_NGINX_WORKER_PROCESSES: ${ASM_NGINX_WORKER_PROCESSES:-2}
      ASM_NGINX_WORKER_RLIMIT_NOFILE: ${ASM_NGINX_WORKER_RLIMIT_NOFILE:-1024}
      ASM_NGINX_WORKER_CONNECTIONS: ${ASM_NGINX_WORKER_CONNECTIONS:-512}
      ASM_NGINX_ERROR_LOG_LEVEL: ${ASM_NGINX_ERROR_LOG_LEVEL:-warn}
      ASM_NGINX_TMPFS_CACHE_SIZE_MB: ${ASM_NGINX_TMPFS_CACHE_SIZE_MB:-128}
      ASM_NGINX_LARGE_CACHE_SIZE_MB: ${ASM_NGINX_LARGE_CACHE_SIZE_MB:-2048}
      ASM_NGINX_LIMIT_CONNECTION: ${ASM_NGINX_LIMIT_CONNECTION:-16}
      ASM_NGINX_LIMIT_RPS: ${ASM_NGINX_LIMIT_RPS:-4}
      ASM_NGINX_LIMIT_RATE_KBS: ${ASM_NGINX_LIMIT_RATE_KBS:-32}
      ASM_NGINX_LIMIT_BURST: ${ASM_NGINX_LIMIT_BURST:-64}
      ASM_NGINX_LIMIT_RATE_AFTER_MB: ${ASM_NGINX_LIMIT_RATE_AFTER_MB:-1}
      ASM_APP_PORT: ${ASM_APP_PORT:-3001}
      ASM_PUBLIC_BASE_URL: ${ASM_PUBLIC_BASE_URL:-/}
      ASM_FRONT_CP_PORT: ${ASM_FRONT_CP_PORT:-3000}
      ASM_FRONT_CP_PATH: ${ASM_FRONT_CP_PATH:-_cp}
      ASM_ACCESS_LOG_COMMENT: ${ASM_ACCESS_LOG_COMMENT:-}
      ASM_PUBLIC_APP_LANG: ${ASM_PUBLIC_APP_LANG:-en}
    tmpfs:
      - /nginx-tmpfs:rw,nodev,nosuid,noexec,noatime,size=${ASM_NGINX_TMPFS_CACHE_SIZE_MB:-192}m
    volumes:
      - ./nginx/templates/default.prod.conf.template:/etc/nginx/templates/default.conf.template
      # - ./app/front-cp/dist:/web-app

  # databases
  htm-redis:
    container_name: htm-redis
    image: redis:6

  htm-mongo:
    container_name: htm-mongo
    image: mongo:4
