export default [
  {
    code: 'AD',
    emoji: '🇦🇩',
    name: 'Andorra',
    nativeName: 'Andorra',
    alpha2Code: 'AD',
  },
  {
    code: 'AE',
    emoji: '🇦🇪',
    name: 'United Arab Emirates',
    nativeName: 'دولة الإمارات العربية المتحدة',
    alpha2Code: 'AE',
  },
  {
    code: 'AF',
    emoji: '🇦🇫',
    name: 'Afghanistan',
    nativeName: 'افغانستان',
    alpha2Code: 'AF',
  },
  {
    code: 'AG',
    emoji: '🇦🇬',
    name: 'Antigua and Barbuda',
    nativeName: 'Antigua and Barbuda',
    alpha2Code: 'AG',
  },
  {
    code: 'AI',
    emoji: '🇦🇮',
    name: 'Anguilla',
    nativeName: 'Anguilla',
    alpha2Code: 'AI',
  },
  {
    code: 'AL',
    emoji: '🇦🇱',
    name: 'Albania',
    nativeName: 'Shqipëria',
    alpha2Code: 'AL',
  },
  {
    code: 'AM',
    emoji: '🇦🇲',
    name: 'Armenia',
    nativeName: 'Հայաստան',
    alpha2Code: 'AM',
  },
  {
    code: 'AO',
    emoji: '🇦🇴',
    name: 'Angola',
    nativeName: 'Angola',
    alpha2Code: 'AO',
  },
  {
    code: 'AQ',
    emoji: '🇦🇶',
    name: 'Antarctica',
    nativeName: 'Antarctica',
    alpha2Code: 'AQ',
  },
  {
    code: 'AR',
    emoji: '🇦🇷',
    name: 'Argentina',
    nativeName: 'Argentina',
    alpha2Code: 'AR',
  },
  {
    code: 'AS',
    emoji: '🇦🇸',
    name: 'American Samoa',
    nativeName: 'American Samoa',
    alpha2Code: 'AS',
  },
  {
    code: 'AT',
    emoji: '🇦🇹',
    name: 'Austria',
    nativeName: 'Österreich',
    alpha2Code: 'AT',
  },
  {
    code: 'AU',
    emoji: '🇦🇺',
    name: 'Australia',
    nativeName: 'Australia',
    alpha2Code: 'AU',
  },
  {
    code: 'AW',
    emoji: '🇦🇼',
    name: 'Aruba',
    nativeName: 'Aruba',
    alpha2Code: 'AW',
  },
  {
    code: 'AX',
    emoji: '🇦🇽',
    name: 'Åland Islands',
    nativeName: 'Åland',
    alpha2Code: 'AX',
  },
  {
    code: 'AZ',
    emoji: '🇦🇿',
    name: 'Azerbaijan',
    nativeName: 'Azərbaycan',
    alpha2Code: 'AZ',
  },
  {
    code: 'BA',
    emoji: '🇧🇦',
    name: 'Bosnia and Herzegovina',
    nativeName: 'Bosna i Hercegovina',
    alpha2Code: 'BA',
  },
  {
    code: 'BB',
    emoji: '🇧🇧',
    name: 'Barbados',
    nativeName: 'Barbados',
    alpha2Code: 'BB',
  },
  {
    code: 'BD',
    emoji: '🇧🇩',
    name: 'Bangladesh',
    nativeName: 'Bangladesh',
    alpha2Code: 'BD',
  },
  {
    code: 'BE',
    emoji: '🇧🇪',
    name: 'Belgium',
    nativeName: 'België',
    alpha2Code: 'BE',
  },
  {
    code: 'BF',
    emoji: '🇧🇫',
    name: 'Burkina Faso',
    nativeName: 'Burkina Faso',
    alpha2Code: 'BF',
  },
  {
    code: 'BG',
    emoji: '🇧🇬',
    name: 'Bulgaria',
    nativeName: 'България',
    alpha2Code: 'BG',
  },
  {
    code: 'BH',
    emoji: '🇧🇭',
    name: 'Bahrain',
    nativeName: '‏البحرين',
    alpha2Code: 'BH',
  },
  {
    code: 'BI',
    emoji: '🇧🇮',
    name: 'Burundi',
    nativeName: 'Burundi',
    alpha2Code: 'BI',
  },
  {
    code: 'BJ',
    emoji: '🇧🇯',
    name: 'Benin',
    nativeName: 'Bénin',
    alpha2Code: 'BJ',
  },
  {
    code: 'BL',
    emoji: '🇧🇱',
    name: 'Saint Barthélemy',
    nativeName: 'Saint-Barthélemy',
    alpha2Code: 'BL',
  },
  {
    code: 'BM',
    emoji: '🇧🇲',
    name: 'Bermuda',
    nativeName: 'Bermuda',
    alpha2Code: 'BM',
  },
  {
    code: 'BN',
    emoji: '🇧🇳',
    name: 'Brunei Darussalam',
    nativeName: 'Negara Brunei Darussalam',
    alpha2Code: 'BN',
  },
  {
    code: 'BO',
    emoji: '🇧🇴',
    name: 'Bolivia (Plurinational State of)',
    nativeName: 'Bolivia',
    alpha2Code: 'BO',
  },
  {
    code: 'BQ',
    emoji: '🇧🇶',
    name: 'Bonaire, Sint Eustatius and Saba',
    nativeName: 'Bonaire',
    alpha2Code: 'BQ',
  },
  {
    code: 'BR',
    emoji: '🇧🇷',
    name: 'Brazil',
    nativeName: 'Brasil',
    alpha2Code: 'BR',
  },
  {
    code: 'BS',
    emoji: '🇧🇸',
    name: 'Bahamas',
    nativeName: 'Bahamas',
    alpha2Code: 'BS',
  },
  {
    code: 'BT',
    emoji: '🇧🇹',
    name: 'Bhutan',
    nativeName: 'ʼbrug-yul',
    alpha2Code: 'BT',
  },
  {
    code: 'BV',
    emoji: '🇧🇻',
    name: 'Bouvet Island',
    nativeName: 'Bouvetøya',
    alpha2Code: 'BV',
  },
  {
    code: 'BW',
    emoji: '🇧🇼',
    name: 'Botswana',
    nativeName: 'Botswana',
    alpha2Code: 'BW',
  },
  {
    code: 'BY',
    emoji: '🇧🇾',
    name: 'Belarus',
    nativeName: 'Белару́сь',
    alpha2Code: 'BY',
  },
  {
    code: 'BZ',
    emoji: '🇧🇿',
    name: 'Belize',
    nativeName: 'Belize',
    alpha2Code: 'BZ',
  },
  {
    code: 'CA',
    emoji: '🇨🇦',
    name: 'Canada',
    nativeName: 'Canada',
    alpha2Code: 'CA',
  },
  {
    code: 'CC',
    emoji: '🇨🇨',
    name: 'Cocos (Keeling) Islands',
    nativeName: 'Cocos (Keeling) Islands',
    alpha2Code: 'CC',
  },
  {
    code: 'CD',
    emoji: '🇨🇩',
    name: 'Congo (Democratic Republic of the)',
    nativeName: 'République démocratique du Congo',
    alpha2Code: 'CD',
  },
  {
    code: 'CF',
    emoji: '🇨🇫',
    name: 'Central African Republic',
    nativeName: 'Ködörösêse tî Bêafrîka',
    alpha2Code: 'CF',
  },
  {
    code: 'CG',
    emoji: '🇨🇬',
    name: 'Congo',
    nativeName: 'République du Congo',
    alpha2Code: 'CG',
  },
  {
    code: 'CH',
    emoji: '🇨🇭',
    name: 'Switzerland',
    nativeName: 'Schweiz',
    alpha2Code: 'CH',
  },
  {
    code: 'CI',
    emoji: '🇨🇮',
    name: "Côte d'Ivoire",
    nativeName: "Côte d'Ivoire",
    alpha2Code: 'CI',
  },
  {
    code: 'CK',
    emoji: '🇨🇰',
    name: 'Cook Islands',
    nativeName: 'Cook Islands',
    alpha2Code: 'CK',
  },
  {
    code: 'CL',
    emoji: '🇨🇱',
    name: 'Chile',
    nativeName: 'Chile',
    alpha2Code: 'CL',
  },
  {
    code: 'CM',
    emoji: '🇨🇲',
    name: 'Cameroon',
    nativeName: 'Cameroon',
    alpha2Code: 'CM',
  },
  {
    code: 'CN',
    emoji: '🇨🇳',
    name: 'China',
    nativeName: '中国',
    alpha2Code: 'CN',
  },
  {
    code: 'CO',
    emoji: '🇨🇴',
    name: 'Colombia',
    nativeName: 'Colombia',
    alpha2Code: 'CO',
  },
  {
    code: 'CR',
    emoji: '🇨🇷',
    name: 'Costa Rica',
    nativeName: 'Costa Rica',
    alpha2Code: 'CR',
  },
  {
    code: 'CU',
    emoji: '🇨🇺',
    name: 'Cuba',
    nativeName: 'Cuba',
    alpha2Code: 'CU',
  },
  {
    code: 'CV',
    emoji: '🇨🇻',
    name: 'Cabo Verde',
    nativeName: 'Cabo Verde',
    alpha2Code: 'CV',
  },
  {
    code: 'CW',
    emoji: '🇨🇼',
    name: 'Curaçao',
    nativeName: 'Curaçao',
    alpha2Code: 'CW',
  },
  {
    code: 'CX',
    emoji: '🇨🇽',
    name: 'Christmas Island',
    nativeName: 'Christmas Island',
    alpha2Code: 'CX',
  },
  {
    code: 'CY',
    emoji: '🇨🇾',
    name: 'Cyprus',
    nativeName: 'Κύπρος',
    alpha2Code: 'CY',
  },
  {
    code: 'CZ',
    emoji: '🇨🇿',
    name: 'Czech Republic',
    nativeName: 'Česká republika',
    alpha2Code: 'CZ',
  },
  {
    code: 'DE',
    emoji: '🇩🇪',
    name: 'Germany',
    nativeName: 'Deutschland',
    alpha2Code: 'DE',
  },
  {
    code: 'DJ',
    emoji: '🇩🇯',
    name: 'Djibouti',
    nativeName: 'Djibouti',
    alpha2Code: 'DJ',
  },
  {
    code: 'DK',
    emoji: '🇩🇰',
    name: 'Denmark',
    nativeName: 'Danmark',
    alpha2Code: 'DK',
  },
  {
    code: 'DM',
    emoji: '🇩🇲',
    name: 'Dominica',
    nativeName: 'Dominica',
    alpha2Code: 'DM',
  },
  {
    code: 'DO',
    emoji: '🇩🇴',
    name: 'Dominican Republic',
    nativeName: 'República Dominicana',
    alpha2Code: 'DO',
  },
  {
    code: 'DZ',
    emoji: '🇩🇿',
    name: 'Algeria',
    nativeName: 'الجزائر',
    alpha2Code: 'DZ',
  },
  {
    code: 'EC',
    emoji: '🇪🇨',
    name: 'Ecuador',
    nativeName: 'Ecuador',
    alpha2Code: 'EC',
  },
  {
    code: 'EE',
    emoji: '🇪🇪',
    name: 'Estonia',
    nativeName: 'Eesti',
    alpha2Code: 'EE',
  },
  {
    code: 'EG',
    emoji: '🇪🇬',
    name: 'Egypt',
    nativeName: 'مصر‎',
    alpha2Code: 'EG',
  },
  {
    code: 'EH',
    emoji: '🇪🇭',
    name: 'Western Sahara',
    nativeName: 'الصحراء الغربية',
    alpha2Code: 'EH',
  },
  {
    code: 'ER',
    emoji: '🇪🇷',
    name: 'Eritrea',
    nativeName: 'ኤርትራ',
    alpha2Code: 'ER',
  },
  {
    code: 'ES',
    emoji: '🇪🇸',
    name: 'Spain',
    nativeName: 'España',
    alpha2Code: 'ES',
  },
  {
    code: 'ET',
    emoji: '🇪🇹',
    name: 'Ethiopia',
    nativeName: 'ኢትዮጵያ',
    alpha2Code: 'ET',
  },
  {
    code: 'EU',
    emoji: '🇪🇺',
  },
  {
    code: 'FI',
    emoji: '🇫🇮',
    name: 'Finland',
    nativeName: 'Suomi',
    alpha2Code: 'FI',
  },
  {
    code: 'FJ',
    emoji: '🇫🇯',
    name: 'Fiji',
    nativeName: 'Fiji',
    alpha2Code: 'FJ',
  },
  {
    code: 'FK',
    emoji: '🇫🇰',
    name: 'Falkland Islands (Malvinas)',
    nativeName: 'Falkland Islands',
    alpha2Code: 'FK',
  },
  {
    code: 'FM',
    emoji: '🇫🇲',
    name: 'Micronesia (Federated States of)',
    nativeName: 'Micronesia',
    alpha2Code: 'FM',
  },
  {
    code: 'FO',
    emoji: '🇫🇴',
    name: 'Faroe Islands',
    nativeName: 'Føroyar',
    alpha2Code: 'FO',
  },
  {
    code: 'FR',
    emoji: '🇫🇷',
    name: 'France',
    nativeName: 'France',
    alpha2Code: 'FR',
  },
  {
    code: 'GA',
    emoji: '🇬🇦',
    name: 'Gabon',
    nativeName: 'Gabon',
    alpha2Code: 'GA',
  },
  {
    code: 'GB',
    emoji: '🇬🇧',
    name: 'United Kingdom of Great Britain and Northern Ireland',
    nativeName: 'United Kingdom',
    alpha2Code: 'GB',
  },
  {
    code: 'GD',
    emoji: '🇬🇩',
    name: 'Grenada',
    nativeName: 'Grenada',
    alpha2Code: 'GD',
  },
  {
    code: 'GE',
    emoji: '🇬🇪',
    name: 'Georgia',
    nativeName: 'საქართველო',
    alpha2Code: 'GE',
  },
  {
    code: 'GF',
    emoji: '🇬🇫',
    name: 'French Guiana',
    nativeName: 'Guyane française',
    alpha2Code: 'GF',
  },
  {
    code: 'GG',
    emoji: '🇬🇬',
    name: 'Guernsey',
    nativeName: 'Guernsey',
    alpha2Code: 'GG',
  },
  {
    code: 'GH',
    emoji: '🇬🇭',
    name: 'Ghana',
    nativeName: 'Ghana',
    alpha2Code: 'GH',
  },
  {
    code: 'GI',
    emoji: '🇬🇮',
    name: 'Gibraltar',
    nativeName: 'Gibraltar',
    alpha2Code: 'GI',
  },
  {
    code: 'GL',
    emoji: '🇬🇱',
    name: 'Greenland',
    nativeName: 'Kalaallit Nunaat',
    alpha2Code: 'GL',
  },
  {
    code: 'GM',
    emoji: '🇬🇲',
    name: 'Gambia',
    nativeName: 'Gambia',
    alpha2Code: 'GM',
  },
  {
    code: 'GN',
    emoji: '🇬🇳',
    name: 'Guinea',
    nativeName: 'Guinée',
    alpha2Code: 'GN',
  },
  {
    code: 'GP',
    emoji: '🇬🇵',
    name: 'Guadeloupe',
    nativeName: 'Guadeloupe',
    alpha2Code: 'GP',
  },
  {
    code: 'GQ',
    emoji: '🇬🇶',
    name: 'Equatorial Guinea',
    nativeName: 'Guinea Ecuatorial',
    alpha2Code: 'GQ',
  },
  {
    code: 'GR',
    emoji: '🇬🇷',
    name: 'Greece',
    nativeName: 'Ελλάδα',
    alpha2Code: 'GR',
  },
  {
    code: 'GS',
    emoji: '🇬🇸',
    name: 'South Georgia and the South Sandwich Islands',
    nativeName: 'South Georgia',
    alpha2Code: 'GS',
  },
  {
    code: 'GT',
    emoji: '🇬🇹',
    name: 'Guatemala',
    nativeName: 'Guatemala',
    alpha2Code: 'GT',
  },
  {
    code: 'GU',
    emoji: '🇬🇺',
    name: 'Guam',
    nativeName: 'Guam',
    alpha2Code: 'GU',
  },
  {
    code: 'GW',
    emoji: '🇬🇼',
    name: 'Guinea-Bissau',
    nativeName: 'Guiné-Bissau',
    alpha2Code: 'GW',
  },
  {
    code: 'GY',
    emoji: '🇬🇾',
    name: 'Guyana',
    nativeName: 'Guyana',
    alpha2Code: 'GY',
  },
  {
    code: 'HK',
    emoji: '🇭🇰',
    name: 'Hong Kong',
    nativeName: '香港',
    alpha2Code: 'HK',
  },
  {
    code: 'HM',
    emoji: '🇭🇲',
    name: 'Heard Island and McDonald Islands',
    nativeName: 'Heard Island and McDonald Islands',
    alpha2Code: 'HM',
  },
  {
    code: 'HN',
    emoji: '🇭🇳',
    name: 'Honduras',
    nativeName: 'Honduras',
    alpha2Code: 'HN',
  },
  {
    code: 'HR',
    emoji: '🇭🇷',
    name: 'Croatia',
    nativeName: 'Hrvatska',
    alpha2Code: 'HR',
  },
  {
    code: 'HT',
    emoji: '🇭🇹',
    name: 'Haiti',
    nativeName: 'Haïti',
    alpha2Code: 'HT',
  },
  {
    code: 'HU',
    emoji: '🇭🇺',
    name: 'Hungary',
    nativeName: 'Magyarország',
    alpha2Code: 'HU',
  },
  {
    code: 'ID',
    emoji: '🇮🇩',
    name: 'Indonesia',
    nativeName: 'Indonesia',
    alpha2Code: 'ID',
  },
  {
    code: 'IE',
    emoji: '🇮🇪',
    name: 'Ireland',
    nativeName: 'Éire',
    alpha2Code: 'IE',
  },
  {
    code: 'IM',
    emoji: '🇮🇲',
    name: 'Isle of Man',
    nativeName: 'Isle of Man',
    alpha2Code: 'IM',
  },
  {
    code: 'IN',
    emoji: '🇮🇳',
    name: 'India',
    nativeName: 'भारत',
    alpha2Code: 'IN',
  },
  {
    code: 'IO',
    emoji: '🇮🇴',
    name: 'British Indian Ocean Territory',
    nativeName: 'British Indian Ocean Territory',
    alpha2Code: 'IO',
  },
  {
    code: 'IQ',
    emoji: '🇮🇶',
    name: 'Iraq',
    nativeName: 'العراق',
    alpha2Code: 'IQ',
  },
  {
    code: 'IR',
    emoji: '🇮🇷',
    name: 'Iran (Islamic Republic of)',
    nativeName: 'ایران',
    alpha2Code: 'IR',
  },
  {
    code: 'IS',
    emoji: '🇮🇸',
    name: 'Iceland',
    nativeName: 'Ísland',
    alpha2Code: 'IS',
  },
  {
    code: 'IT',
    emoji: '🇮🇹',
    name: 'Italy',
    nativeName: 'Italia',
    alpha2Code: 'IT',
  },
  {
    code: 'JE',
    emoji: '🇯🇪',
    name: 'Jersey',
    nativeName: 'Jersey',
    alpha2Code: 'JE',
  },
  {
    code: 'JM',
    emoji: '🇯🇲',
    name: 'Jamaica',
    nativeName: 'Jamaica',
    alpha2Code: 'JM',
  },
  {
    code: 'JO',
    emoji: '🇯🇴',
    name: 'Jordan',
    nativeName: 'الأردن',
    alpha2Code: 'JO',
  },
  {
    code: 'JP',
    emoji: '🇯🇵',
    name: 'Japan',
    nativeName: '日本',
    alpha2Code: 'JP',
  },
  {
    code: 'KE',
    emoji: '🇰🇪',
    name: 'Kenya',
    nativeName: 'Kenya',
    alpha2Code: 'KE',
  },
  {
    code: 'KG',
    emoji: '🇰🇬',
    name: 'Kyrgyzstan',
    nativeName: 'Кыргызстан',
    alpha2Code: 'KG',
  },
  {
    code: 'KH',
    emoji: '🇰🇭',
    name: 'Cambodia',
    nativeName: 'Kâmpŭchéa',
    alpha2Code: 'KH',
  },
  {
    code: 'KI',
    emoji: '🇰🇮',
    name: 'Kiribati',
    nativeName: 'Kiribati',
    alpha2Code: 'KI',
  },
  {
    code: 'KM',
    emoji: '🇰🇲',
    name: 'Comoros',
    nativeName: 'Komori',
    alpha2Code: 'KM',
  },
  {
    code: 'KN',
    emoji: '🇰🇳',
    name: 'Saint Kitts and Nevis',
    nativeName: 'Saint Kitts and Nevis',
    alpha2Code: 'KN',
  },
  {
    code: 'KP',
    emoji: '🇰🇵',
    name: "Korea (Democratic People's Republic of)",
    nativeName: '북한',
    alpha2Code: 'KP',
  },
  {
    code: 'KR',
    emoji: '🇰🇷',
    name: 'Korea (Republic of)',
    nativeName: '대한민국',
    alpha2Code: 'KR',
  },
  {
    code: 'KW',
    emoji: '🇰🇼',
    name: 'Kuwait',
    nativeName: 'الكويت',
    alpha2Code: 'KW',
  },
  {
    code: 'KY',
    emoji: '🇰🇾',
    name: 'Cayman Islands',
    nativeName: 'Cayman Islands',
    alpha2Code: 'KY',
  },
  {
    code: 'KZ',
    emoji: '🇰🇿',
    name: 'Kazakhstan',
    nativeName: 'Қазақстан',
    alpha2Code: 'KZ',
  },
  {
    code: 'LA',
    emoji: '🇱🇦',
    name: "Lao People's Democratic Republic",
    nativeName: 'ສປປລາວ',
    alpha2Code: 'LA',
  },
  {
    code: 'LB',
    emoji: '🇱🇧',
    name: 'Lebanon',
    nativeName: 'لبنان',
    alpha2Code: 'LB',
  },
  {
    code: 'LC',
    emoji: '🇱🇨',
    name: 'Saint Lucia',
    nativeName: 'Saint Lucia',
    alpha2Code: 'LC',
  },
  {
    code: 'LI',
    emoji: '🇱🇮',
    name: 'Liechtenstein',
    nativeName: 'Liechtenstein',
    alpha2Code: 'LI',
  },
  {
    code: 'LK',
    emoji: '🇱🇰',
    name: 'Sri Lanka',
    nativeName: 'śrī laṃkāva',
    alpha2Code: 'LK',
  },
  {
    code: 'LR',
    emoji: '🇱🇷',
    name: 'Liberia',
    nativeName: 'Liberia',
    alpha2Code: 'LR',
  },
  {
    code: 'LS',
    emoji: '🇱🇸',
    name: 'Lesotho',
    nativeName: 'Lesotho',
    alpha2Code: 'LS',
  },
  {
    code: 'LT',
    emoji: '🇱🇹',
    name: 'Lithuania',
    nativeName: 'Lietuva',
    alpha2Code: 'LT',
  },
  {
    code: 'LU',
    emoji: '🇱🇺',
    name: 'Luxembourg',
    nativeName: 'Luxembourg',
    alpha2Code: 'LU',
  },
  {
    code: 'LV',
    emoji: '🇱🇻',
    name: 'Latvia',
    nativeName: 'Latvija',
    alpha2Code: 'LV',
  },
  {
    code: 'LY',
    emoji: '🇱🇾',
    name: 'Libya',
    nativeName: '‏ليبيا',
    alpha2Code: 'LY',
  },
  {
    code: 'MA',
    emoji: '🇲🇦',
    name: 'Morocco',
    nativeName: 'المغرب',
    alpha2Code: 'MA',
  },
  {
    code: 'MC',
    emoji: '🇲🇨',
    name: 'Monaco',
    nativeName: 'Monaco',
    alpha2Code: 'MC',
  },
  {
    code: 'MD',
    emoji: '🇲🇩',
    name: 'Moldova (Republic of)',
    nativeName: 'Moldova',
    alpha2Code: 'MD',
  },
  {
    code: 'ME',
    emoji: '🇲🇪',
    name: 'Montenegro',
    nativeName: 'Црна Гора',
    alpha2Code: 'ME',
  },
  {
    code: 'MF',
    emoji: '🇲🇫',
    name: 'Saint Martin (French part)',
    nativeName: 'Saint-Martin',
    alpha2Code: 'MF',
  },
  {
    code: 'MG',
    emoji: '🇲🇬',
    name: 'Madagascar',
    nativeName: 'Madagasikara',
    alpha2Code: 'MG',
  },
  {
    code: 'MH',
    emoji: '🇲🇭',
    name: 'Marshall Islands',
    nativeName: 'M̧ajeļ',
    alpha2Code: 'MH',
  },
  {
    code: 'MK',
    emoji: '🇲🇰',
    name: 'Macedonia (the former Yugoslav Republic of)',
    nativeName: 'Македонија',
    alpha2Code: 'MK',
  },
  {
    code: 'ML',
    emoji: '🇲🇱',
    name: 'Mali',
    nativeName: 'Mali',
    alpha2Code: 'ML',
  },
  {
    code: 'MM',
    emoji: '🇲🇲',
    name: 'Myanmar',
    nativeName: 'Myanma',
    alpha2Code: 'MM',
  },
  {
    code: 'MN',
    emoji: '🇲🇳',
    name: 'Mongolia',
    nativeName: 'Монгол улс',
    alpha2Code: 'MN',
  },
  {
    code: 'MO',
    emoji: '🇲🇴',
    name: 'Macao',
    nativeName: '澳門',
    alpha2Code: 'MO',
  },
  {
    code: 'MP',
    emoji: '🇲🇵',
    name: 'Northern Mariana Islands',
    nativeName: 'Northern Mariana Islands',
    alpha2Code: 'MP',
  },
  {
    code: 'MQ',
    emoji: '🇲🇶',
    name: 'Martinique',
    nativeName: 'Martinique',
    alpha2Code: 'MQ',
  },
  {
    code: 'MR',
    emoji: '🇲🇷',
    name: 'Mauritania',
    nativeName: 'موريتانيا',
    alpha2Code: 'MR',
  },
  {
    code: 'MS',
    emoji: '🇲🇸',
    name: 'Montserrat',
    nativeName: 'Montserrat',
    alpha2Code: 'MS',
  },
  {
    code: 'MT',
    emoji: '🇲🇹',
    name: 'Malta',
    nativeName: 'Malta',
    alpha2Code: 'MT',
  },
  {
    code: 'MU',
    emoji: '🇲🇺',
    name: 'Mauritius',
    nativeName: 'Maurice',
    alpha2Code: 'MU',
  },
  {
    code: 'MV',
    emoji: '🇲🇻',
    name: 'Maldives',
    nativeName: 'Maldives',
    alpha2Code: 'MV',
  },
  {
    code: 'MW',
    emoji: '🇲🇼',
    name: 'Malawi',
    nativeName: 'Malawi',
    alpha2Code: 'MW',
  },
  {
    code: 'MX',
    emoji: '🇲🇽',
    name: 'Mexico',
    nativeName: 'México',
    alpha2Code: 'MX',
  },
  {
    code: 'MY',
    emoji: '🇲🇾',
    name: 'Malaysia',
    nativeName: 'Malaysia',
    alpha2Code: 'MY',
  },
  {
    code: 'MZ',
    emoji: '🇲🇿',
    name: 'Mozambique',
    nativeName: 'Moçambique',
    alpha2Code: 'MZ',
  },
  {
    code: 'NA',
    emoji: '🇳🇦',
    name: 'Namibia',
    nativeName: 'Namibia',
    alpha2Code: 'NA',
  },
  {
    code: 'NC',
    emoji: '🇳🇨',
    name: 'New Caledonia',
    nativeName: 'Nouvelle-Calédonie',
    alpha2Code: 'NC',
  },
  {
    code: 'NE',
    emoji: '🇳🇪',
    name: 'Niger',
    nativeName: 'Niger',
    alpha2Code: 'NE',
  },
  {
    code: 'NF',
    emoji: '🇳🇫',
    name: 'Norfolk Island',
    nativeName: 'Norfolk Island',
    alpha2Code: 'NF',
  },
  {
    code: 'NG',
    emoji: '🇳🇬',
    name: 'Nigeria',
    nativeName: 'Nigeria',
    alpha2Code: 'NG',
  },
  {
    code: 'NI',
    emoji: '🇳🇮',
    name: 'Nicaragua',
    nativeName: 'Nicaragua',
    alpha2Code: 'NI',
  },
  {
    code: 'NL',
    emoji: '🇳🇱',
    name: 'Netherlands',
    nativeName: 'Nederland',
    alpha2Code: 'NL',
  },
  {
    code: 'NO',
    emoji: '🇳🇴',
    name: 'Norway',
    nativeName: 'Norge',
    alpha2Code: 'NO',
  },
  {
    code: 'NP',
    emoji: '🇳🇵',
    name: 'Nepal',
    nativeName: 'नेपाल',
    alpha2Code: 'NP',
  },
  {
    code: 'NR',
    emoji: '🇳🇷',
    name: 'Nauru',
    nativeName: 'Nauru',
    alpha2Code: 'NR',
  },
  {
    code: 'NU',
    emoji: '🇳🇺',
    name: 'Niue',
    nativeName: 'Niuē',
    alpha2Code: 'NU',
  },
  {
    code: 'NZ',
    emoji: '🇳🇿',
    name: 'New Zealand',
    nativeName: 'New Zealand',
    alpha2Code: 'NZ',
  },
  {
    code: 'OM',
    emoji: '🇴🇲',
    name: 'Oman',
    nativeName: 'عمان',
    alpha2Code: 'OM',
  },
  {
    code: 'PA',
    emoji: '🇵🇦',
    name: 'Panama',
    nativeName: 'Panamá',
    alpha2Code: 'PA',
  },
  {
    code: 'PE',
    emoji: '🇵🇪',
    name: 'Peru',
    nativeName: 'Perú',
    alpha2Code: 'PE',
  },
  {
    code: 'PF',
    emoji: '🇵🇫',
    name: 'French Polynesia',
    nativeName: 'Polynésie française',
    alpha2Code: 'PF',
  },
  {
    code: 'PG',
    emoji: '🇵🇬',
    name: 'Papua New Guinea',
    nativeName: 'Papua Niugini',
    alpha2Code: 'PG',
  },
  {
    code: 'PH',
    emoji: '🇵🇭',
    name: 'Philippines',
    nativeName: 'Pilipinas',
    alpha2Code: 'PH',
  },
  {
    code: 'PK',
    emoji: '🇵🇰',
    name: 'Pakistan',
    nativeName: 'Pakistan',
    alpha2Code: 'PK',
  },
  {
    code: 'PL',
    emoji: '🇵🇱',
    name: 'Poland',
    nativeName: 'Polska',
    alpha2Code: 'PL',
  },
  {
    code: 'PM',
    emoji: '🇵🇲',
    name: 'Saint Pierre and Miquelon',
    nativeName: 'Saint-Pierre-et-Miquelon',
    alpha2Code: 'PM',
  },
  {
    code: 'PN',
    emoji: '🇵🇳',
    name: 'Pitcairn',
    nativeName: 'Pitcairn Islands',
    alpha2Code: 'PN',
  },
  {
    code: 'PR',
    emoji: '🇵🇷',
    name: 'Puerto Rico',
    nativeName: 'Puerto Rico',
    alpha2Code: 'PR',
  },
  {
    code: 'PS',
    emoji: '🇵🇸',
    name: 'Palestine, State of',
    nativeName: 'فلسطين',
    alpha2Code: 'PS',
  },
  {
    code: 'PT',
    emoji: '🇵🇹',
    name: 'Portugal',
    nativeName: 'Portugal',
    alpha2Code: 'PT',
  },
  {
    code: 'PW',
    emoji: '🇵🇼',
    name: 'Palau',
    nativeName: 'Palau',
    alpha2Code: 'PW',
  },
  {
    code: 'PY',
    emoji: '🇵🇾',
    name: 'Paraguay',
    nativeName: 'Paraguay',
    alpha2Code: 'PY',
  },
  {
    code: 'QA',
    emoji: '🇶🇦',
    name: 'Qatar',
    nativeName: 'قطر',
    alpha2Code: 'QA',
  },
  {
    code: 'RE',
    emoji: '🇷🇪',
    name: 'Réunion',
    nativeName: 'La Réunion',
    alpha2Code: 'RE',
  },
  {
    code: 'RO',
    emoji: '🇷🇴',
    name: 'Romania',
    nativeName: 'România',
    alpha2Code: 'RO',
  },
  {
    code: 'RS',
    emoji: '🇷🇸',
    name: 'Serbia',
    nativeName: 'Србија',
    alpha2Code: 'RS',
  },
  {
    code: 'RU',
    emoji: '🇷🇺',
    name: 'Russian Federation',
    nativeName: 'Россия',
    alpha2Code: 'RU',
  },
  {
    code: 'RW',
    emoji: '🇷🇼',
    name: 'Rwanda',
    nativeName: 'Rwanda',
    alpha2Code: 'RW',
  },
  {
    code: 'SA',
    emoji: '🇸🇦',
    name: 'Saudi Arabia',
    nativeName: 'العربية السعودية',
    alpha2Code: 'SA',
  },
  {
    code: 'SB',
    emoji: '🇸🇧',
    name: 'Solomon Islands',
    nativeName: 'Solomon Islands',
    alpha2Code: 'SB',
  },
  {
    code: 'SC',
    emoji: '🇸🇨',
    name: 'Seychelles',
    nativeName: 'Seychelles',
    alpha2Code: 'SC',
  },
  {
    code: 'SD',
    emoji: '🇸🇩',
    name: 'Sudan',
    nativeName: 'السودان',
    alpha2Code: 'SD',
  },
  {
    code: 'SE',
    emoji: '🇸🇪',
    name: 'Sweden',
    nativeName: 'Sverige',
    alpha2Code: 'SE',
  },
  {
    code: 'SG',
    emoji: '🇸🇬',
    name: 'Singapore',
    nativeName: 'Singapore',
    alpha2Code: 'SG',
  },
  {
    code: 'SH',
    emoji: '🇸🇭',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    nativeName: 'Saint Helena',
    alpha2Code: 'SH',
  },
  {
    code: 'SI',
    emoji: '🇸🇮',
    name: 'Slovenia',
    nativeName: 'Slovenija',
    alpha2Code: 'SI',
  },
  {
    code: 'SJ',
    emoji: '🇸🇯',
    name: 'Svalbard and Jan Mayen',
    nativeName: 'Svalbard og Jan Mayen',
    alpha2Code: 'SJ',
  },
  {
    code: 'SK',
    emoji: '🇸🇰',
    name: 'Slovakia',
    nativeName: 'Slovensko',
    alpha2Code: 'SK',
  },
  {
    code: 'SL',
    emoji: '🇸🇱',
    name: 'Sierra Leone',
    nativeName: 'Sierra Leone',
    alpha2Code: 'SL',
  },
  {
    code: 'SM',
    emoji: '🇸🇲',
    name: 'San Marino',
    nativeName: 'San Marino',
    alpha2Code: 'SM',
  },
  {
    code: 'SN',
    emoji: '🇸🇳',
    name: 'Senegal',
    nativeName: 'Sénégal',
    alpha2Code: 'SN',
  },
  {
    code: 'SO',
    emoji: '🇸🇴',
    name: 'Somalia',
    nativeName: 'Soomaaliya',
    alpha2Code: 'SO',
  },
  {
    code: 'SR',
    emoji: '🇸🇷',
    name: 'Suriname',
    nativeName: 'Suriname',
    alpha2Code: 'SR',
  },
  {
    code: 'SS',
    emoji: '🇸🇸',
    name: 'South Sudan',
    nativeName: 'South Sudan',
    alpha2Code: 'SS',
  },
  {
    code: 'ST',
    emoji: '🇸🇹',
    name: 'Sao Tome and Principe',
    nativeName: 'São Tomé e Príncipe',
    alpha2Code: 'ST',
  },
  {
    code: 'SV',
    emoji: '🇸🇻',
    name: 'El Salvador',
    nativeName: 'El Salvador',
    alpha2Code: 'SV',
  },
  {
    code: 'SX',
    emoji: '🇸🇽',
    name: 'Sint Maarten (Dutch part)',
    nativeName: 'Sint Maarten',
    alpha2Code: 'SX',
  },
  {
    code: 'SY',
    emoji: '🇸🇾',
    name: 'Syrian Arab Republic',
    nativeName: 'سوريا',
    alpha2Code: 'SY',
  },
  {
    code: 'SZ',
    emoji: '🇸🇿',
    name: 'Swaziland',
    nativeName: 'Swaziland',
    alpha2Code: 'SZ',
  },
  {
    code: 'TC',
    emoji: '🇹🇨',
    name: 'Turks and Caicos Islands',
    nativeName: 'Turks and Caicos Islands',
    alpha2Code: 'TC',
  },
  {
    code: 'TD',
    emoji: '🇹🇩',
    name: 'Chad',
    nativeName: 'Tchad',
    alpha2Code: 'TD',
  },
  {
    code: 'TF',
    emoji: '🇹🇫',
    name: 'French Southern Territories',
    nativeName: 'Territoire des Terres australes et antarctiques françaises',
    alpha2Code: 'TF',
  },
  {
    code: 'TG',
    emoji: '🇹🇬',
    name: 'Togo',
    nativeName: 'Togo',
    alpha2Code: 'TG',
  },
  {
    code: 'TH',
    emoji: '🇹🇭',
    name: 'Thailand',
    nativeName: 'ประเทศไทย',
    alpha2Code: 'TH',
  },
  {
    code: 'TJ',
    emoji: '🇹🇯',
    name: 'Tajikistan',
    nativeName: 'Тоҷикистон',
    alpha2Code: 'TJ',
  },
  {
    code: 'TK',
    emoji: '🇹🇰',
    name: 'Tokelau',
    nativeName: 'Tokelau',
    alpha2Code: 'TK',
  },
  {
    code: 'TL',
    emoji: '🇹🇱',
    name: 'Timor-Leste',
    nativeName: 'Timor-Leste',
    alpha2Code: 'TL',
  },
  {
    code: 'TM',
    emoji: '🇹🇲',
    name: 'Turkmenistan',
    nativeName: 'Türkmenistan',
    alpha2Code: 'TM',
  },
  {
    code: 'TN',
    emoji: '🇹🇳',
    name: 'Tunisia',
    nativeName: 'تونس',
    alpha2Code: 'TN',
  },
  {
    code: 'TO',
    emoji: '🇹🇴',
    name: 'Tonga',
    nativeName: 'Tonga',
    alpha2Code: 'TO',
  },
  {
    code: 'TR',
    emoji: '🇹🇷',
    name: 'Turkey',
    nativeName: 'Türkiye',
    alpha2Code: 'TR',
  },
  {
    code: 'TT',
    emoji: '🇹🇹',
    name: 'Trinidad and Tobago',
    nativeName: 'Trinidad and Tobago',
    alpha2Code: 'TT',
  },
  {
    code: 'TV',
    emoji: '🇹🇻',
    name: 'Tuvalu',
    nativeName: 'Tuvalu',
    alpha2Code: 'TV',
  },
  {
    code: 'TW',
    emoji: '🇹🇼',
    name: 'Taiwan',
    nativeName: '臺灣',
    alpha2Code: 'TW',
  },
  {
    code: 'TZ',
    emoji: '🇹🇿',
    name: 'Tanzania, United Republic of',
    nativeName: 'Tanzania',
    alpha2Code: 'TZ',
  },
  {
    code: 'UA',
    emoji: '🇺🇦',
    name: 'Ukraine',
    nativeName: 'Україна',
    alpha2Code: 'UA',
  },
  {
    code: 'UG',
    emoji: '🇺🇬',
    name: 'Uganda',
    nativeName: 'Uganda',
    alpha2Code: 'UG',
  },
  {
    code: 'UM',
    emoji: '🇺🇲',
    name: 'United States Minor Outlying Islands',
    nativeName: 'United States Minor Outlying Islands',
    alpha2Code: 'UM',
  },
  {
    code: 'US',
    emoji: '🇺🇸',
    name: 'United States of America',
    nativeName: 'United States',
    alpha2Code: 'US',
  },
  {
    code: 'UY',
    emoji: '🇺🇾',
    name: 'Uruguay',
    nativeName: 'Uruguay',
    alpha2Code: 'UY',
  },
  {
    code: 'UZ',
    emoji: '🇺🇿',
    name: 'Uzbekistan',
    nativeName: 'O‘zbekiston',
    alpha2Code: 'UZ',
  },
  {
    code: 'VA',
    emoji: '🇻🇦',
    name: 'Holy See',
    nativeName: 'Sancta Sedes',
    alpha2Code: 'VA',
  },
  {
    code: 'VC',
    emoji: '🇻🇨',
    name: 'Saint Vincent and the Grenadines',
    nativeName: 'Saint Vincent and the Grenadines',
    alpha2Code: 'VC',
  },
  {
    code: 'VE',
    emoji: '🇻🇪',
    name: 'Venezuela (Bolivarian Republic of)',
    nativeName: 'Venezuela',
    alpha2Code: 'VE',
  },
  {
    code: 'VG',
    emoji: '🇻🇬',
    name: 'Virgin Islands (British)',
    nativeName: 'British Virgin Islands',
    alpha2Code: 'VG',
  },
  {
    code: 'VI',
    emoji: '🇻🇮',
    name: 'Virgin Islands (U.S.)',
    nativeName: 'Virgin Islands of the United States',
    alpha2Code: 'VI',
  },
  {
    code: 'VN',
    emoji: '🇻🇳',
    name: 'Viet Nam',
    nativeName: 'Việt Nam',
    alpha2Code: 'VN',
  },
  {
    code: 'VU',
    emoji: '🇻🇺',
    name: 'Vanuatu',
    nativeName: 'Vanuatu',
    alpha2Code: 'VU',
  },
  {
    code: 'WF',
    emoji: '🇼🇫',
    name: 'Wallis and Futuna',
    nativeName: 'Wallis et Futuna',
    alpha2Code: 'WF',
  },
  {
    code: 'WS',
    emoji: '🇼🇸',
    name: 'Samoa',
    nativeName: 'Samoa',
    alpha2Code: 'WS',
  },
  {
    code: 'XK',
    emoji: '🇽🇰',
    name: 'Republic of Kosovo',
    nativeName: 'Republika e Kosovës',
    alpha2Code: 'XK',
  },
  {
    code: 'YE',
    emoji: '🇾🇪',
    name: 'Yemen',
    nativeName: 'اليَمَن',
    alpha2Code: 'YE',
  },
  {
    code: 'YT',
    emoji: '🇾🇹',
    name: 'Mayotte',
    nativeName: 'Mayotte',
    alpha2Code: 'YT',
  },
  {
    code: 'ZA',
    emoji: '🇿🇦',
    name: 'South Africa',
    nativeName: 'South Africa',
    alpha2Code: 'ZA',
  },
  {
    code: 'ZM',
    emoji: '🇿🇲',
    name: 'Zambia',
    nativeName: 'Zambia',
    alpha2Code: 'ZM',
  },
  {
    code: 'ZW',
    emoji: '🇿🇼',
    name: 'Zimbabwe',
    nativeName: 'Zimbabwe',
    alpha2Code: 'ZW',
  },
];
